### PR TITLE
chore(deps): update deps and change JSON lib Poison -> Jason and mix format

### PR DESCRIPTION
**Pull request by seantanly**

### CODE REVIEW

**Comment by pkinney** [comment]
I'll merge this in then fix the failure before publishing.  It's just that I haven't updated the Elixir version in here for a while.

JSON is only used to decode the test file, so I can move the Jason dependency to `only: :dev` at the same time.

Thank you for the PR!

**Comment by pkinney** [comment]
Published as v. 1.0.0

**Comment by seantanly** [comment]
Thanks for the new release! 👍 
Perhaps the `README.md` should be updated as well to 
```
[{:simplify, "~> 1.0"}]
```

**Comment by pkinney** [comment]
Done, thanks!

**Pull request merged**
